# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### Get request with a header
GET http://127.0.0.1:8080/sd/health
Accept: application/json

###
GET http://127.0.0.1:8080/sd/disk
Accept: application/json

###
GET http://127.0.0.1:8080/sd/cpu
Accept: application/json
###

#
POST http://127.0.0.1:8080/v1/user
Content-Type: application/json

###
POST http://127.0.0.1:8080/v1/user
Content-Type: application/json

{
    "username":"asd",
    "password":"111"
}

###
POST http://127.0.0.1:8080/v1/user/admin2?desc=hellodesc
Content-Type: application/json

{
  "username":"asd",
  "password":"111"
}

###
# 用户创建
POST http://127.0.0.1:8080/v1/user
Content-Type: application/json

{
  "username": "q6",
  "password": "123456"
}

###
# 用户单个查询
GET http://127.0.0.1:8080/v1/user/q3
Accept: application/json

###


#删除用户
DELETE http://127.0.0.1:8080/v1/user/2
Content-Type: application/json

###
# 获取用户列表
GET http://127.0.0.1:8080/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjcxOTAwODcsImlkIjo3LCJuYmYiOjE1NjcxOTAwODcsInVzZXJuYW1lIjoicTUifQ.Kl5WeyGiirSwyS6s8zoZmIrkcBKgc8mGwPbfEOC_u34

{
  "username": "q",
  "offset": 0,
  "limit": 10
}


###
# 用户登入 测试jwt鉴权 1
POST http://127.0.0.1:8080/login
Content-Type: application/json

{
  "username": "q5",
  "password": "123456"
}

###
# 用户登入 测试jwt鉴权 2
GET http://127.0.0.1:8080/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjcxOTAwODcsImlkIjo3LCJuYmYiOjE1NjcxOTAwODcsInVzZXJuYW1lIjoicTUifQ.Kl5WeyGiirSwyS6s8zoZmIrkcBKgc8mGwPbfEOC_u34
Content-Type: application/json

{
  "username": "q",
  "offset": 0,
  "limit": 10
}

###

# 负载均衡测试 用户登入 测试jwt鉴权 2
GET http://apiserver.com/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjcxOTAwODcsImlkIjo3LCJuYmYiOjE1NjcxOTAwODcsInVzZXJuYW1lIjoicTUifQ.Kl5WeyGiirSwyS6s8zoZmIrkcBKgc8mGwPbfEOC_u34
Content-Type: application/json

{
  "username": "q",
  "offset": 0,
  "limit": 10
}

###